1
ВНИМАНИЕ! ОБЕЗЪЯНЫ!\nЕсли кто то из ваших знакомых использует Updatez и AntiCloud то переводите из на этот мод или на моды в https://t.me/antiupdatez
СПАСИБО!\n в https://t.me/antiupdatez вы найдете самые свежие моды
https://t.me/antiupdatez
